CREATE TABLE USERS (
	ID INT NOT NULL, 
	USERNAME VARCHAR(150) NOT NULL, 
	PASSWORD VARCHAR(150) NOT NULL, 
	ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL, 
	ACCOUNT_NON_LOCKED BOOLEAN NOT NULL, 
	CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL, 
	ENABLED BOOLEAN NOT NULL
);